version: '3.8'

services:
  api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db2
    environment:
      - DATABASE_URL=postgresql://postgres2:password2@db2:5432/applications_db
      - DB_HOST=db2
      - DB_PORT=5432

  db2:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: applications_db
    ports:
      - "5433:5432"
